services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - ai
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=aiplatform
      - JWT_SECRET=${JWT_SECRET}
      - PYTHON_SERVICE_URL=http://ai:8000
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - IMAGE_API=${IMAGE_API}

  ai:
    build: ./ai
    ports:
      - "8000:8000"
    environment:
      - IMAGE_API=${IMAGE_API}

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080