services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - ai
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=aiplatform
      - JWT_SECRET=${JWT_SECRET}
      - PYTHON_SERVICE_URL=http://ai:8000
      - IMAGE_API=${IMAGE_API}

  ai:
    build: ./ai
    ports:
      - "8000:8000"
    environment:
      - IMAGE_API=${IMAGE_API}

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  mongo_data: